Entity/Report.php
<?php

namespace Terminalbd\ProcurementBundle\Entity;

use App\Entity\Application\GenericMaster;
use App\Entity\Application\Procurement;
use App\Entity\Application\SecurityBilling;
use App\Entity\Core\Customer;
use App\Entity\Admin\Location;
use Terminalbd\ProcurementBundleBundle\Repository\ParticularRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="Terminalbd\ProcurementBundle\Repository\ReportRepository")
 * @ORM\Table(name="procu_report")
 * @UniqueEntity(fields={"slug","config"}, message="This particular slug must be unique")
 * @author Md Shafiqul Islam <shafiqabs@gmail.com>
 */
class Report
{

    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;


}

Entity/RequisitionSlip.php
<?php

namespace Terminalbd\ProcurementBundle\Entity;


use App\Entity\Admin\Bank;
use App\Entity\Application\Procurement;
use App\Entity\Core\Employee;
use App\Entity\Core\Setting;
use App\Entity\Domain\Branch;
use App\Entity\Domain\ModuleProcess;
use App\Entity\Domain\Vendor;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Date;
use Terminalbd\ProcurementBundle\Form\FundForcastFormType;
use Terminalbd\ProcurementBundle\Entity\ProcurementCondition;
use Terminalbd\ProcurementBundle\Entity\ProcurementProcess;

/**
 * RequisitionSlip
 *
 * @ORM\Table(name="procu_requisition_slip")
 * @ORM\Entity(repositoryClass="Terminalbd\ProcurementBundle\Repository\RequisitionSlipRepository")
 */
class RequisitionSlip
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var Procurement
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Application\Procurement")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $config;


    /**
     * @var ProcurementCondition
     * @ORM\ManyToOne(targetEntity="Terminalbd\ProcurementBundle\Entity\ProcurementCondition")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $condition;

    /**
     * @var ProcurementProcess
     *
     * @ORM\OneToOne(targetEntity="Terminalbd\ProcurementBundle\Entity\ProcurementProcess")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="approveProcess_id", referencedColumnName="id", onDelete="SET NULL", nullable=true)
     * })
     */
    private $approveProcess;


    /**
     * @var JobRequisitionAdditionalItem
     *
     * @ORM\OneToMany(targetEntity="Terminalbd\ProcurementBundle\Entity\JobRequisitionAdditionalItem", mappedBy="requisitionSlip")
     * @ORM\OrderBy({"created" = "DESC"})
     */
    private $additionalItems;

    /**
     * @var RequisitionSlip
     *
     * @ORM\ManyToOne(targetEntity="Terminalbd\ProcurementBundle\Entity\RequisitionSlip")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $reverse;

    /**
     * @var RequisitionSlip
     *
     * @ORM\ManyToOne(targetEntity="Terminalbd\ProcurementBundle\Entity\RequisitionSlip")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $fromReverse;



    /**
     * @var Branch
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Domain\Branch")
     */
    private $company;


     /**
     * @var Branch
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Domain\Branch")
     */
    private $companyUnit;

    /**
     * @var integer
     * @ORM\Column(type="integer",nullable=true)
     */
    private $processOrdering = 0;

    /**
     * @var ModuleProcess
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Domain\ModuleProcess")
     */
    private $moduleProcess;

    /**
     * @var Setting
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $department;

    /**
     * @var Setting
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private $processDepartment;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     */
    private $process='New';

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     */
    private $requisitionMode='AAP';

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     */
    private $mode='benificiery';


    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isDelete = 0;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     */
    private $module ="requisition-slip";
    

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     */
    private $waitingProcess='New';

    /**
     * @var float
     *
     * @ORM\Column(name="total", type="float",nullable=true)
     */
    private $total = 0;

    /**
     * @var float
     * @ORM\Column(type="float",nullable=true)
     */
    private $subTotal=0;

    /**
     * @var integer
     *
     * @ORM\Column(name="code", type="integer",  nullable=true)
     */
    private $code;

     /**
     * @var integer
     *
     * @ORM\Column(type="integer",  nullable=true)
     */
    private $targetDays = 0;

     /**
     * @var boolean
     *
     * @ORM\Column(name="status", type="boolean",  nullable=true)
     */
    private $status;


     /**
     * @var boolean
     *
     * @ORM\Column(name="migrated", type="boolean",  nullable=true)
     */
    private  $migrated= 0;

    /**
     * @var Employee
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Employee")
     **/
    private  $benificiery;


    /**
     * @var Vendor
     * @ORM\ManyToOne(targetEntity="App\Entity\Domain\Vendor")
     **/
    private  $vendor;


    /**
     * @Gedmo\Blameable(on="create")
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     **/
    private  $createdBy;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     **/
    private  $preparedBy;

     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     **/
    private  $deletedBy;

    /**
     * @var string
     * @ORM\Column(type="text",nullable=true)
     */
    private $deleteContent;

     /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     **/
    private  $rejectedBy;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     **/
    private  $approvedBy;

    /**
     * @var Date
     *
     * @ORM\Column(type="date", nullable=true)
     */
    private $paymentDate;


    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable = true)
     */
    private $description;


    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable = true)
     */
    private $content;

     /**
     * @var string
     *
     * @ORM\Column(type="text",nullable = true)
     */
    private $comment;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     **/
    private  $reportTo;

    /**
     * @var string
     * @ORM\Column(type="string",nullable=true)
     */
    private $requisitionNo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $path;


    /**
     * @Assert\File(maxSize="8388608")
     */
    protected $file;

    /**
     * @var Date
     *
     * @ORM\Column(name="expectedDate", type="date", nullable=true)
     */
    private $expectedDate;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="created", type="datetime")
     */
    private $created;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="generatedDate", type="datetime", nullable=true)
     */
    private $generatedDate;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="updated", type="datetime")
     */
    private $updated;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return ProcurementProcess
     */
    public function getApproveProcess()
    {
        return $this->approveProcess;
    }

    /**
     * @param ProcurementProcess $approveProcess
     */
    public function setApproveProcess($approveProcess)
    {
        $this->approveProcess = $approveProcess;
    }

    /**
     * @return AccountBank
     */
    public function getBankAccount()
    {
        return $this->bankAccount;
    }

    /**
     * @param AccountBank $bankAccount
     */
    public function setBankAccount($bankAccount)
    {
        $this->bankAccount = $bankAccount;
    }

    /**
     * @return Branch
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * @param Branch $company
     */
    public function setCompany(Branch $company)
    {
        $this->company = $company;
    }

    /**
     * @return Particular
     */
    public function getOperationMode()
    {
        return $this->operationMode;
    }

    /**
     * @param Particular $operationMode
     */
    public function setOperationMode(Particular $operationMode)
    {
        $this->operationMode = $operationMode;
    }


    /**
     * @return int
     */
    public function getProcessOrdering()
    {
        return $this->processOrdering;
    }

    /**
     * @param int $processOrdering
     */
    public function setProcessOrdering(int $processOrdering)
    {
        $this->processOrdering = $processOrdering;
    }

    /**
     * @return ModuleProcess
     */
    public function getModuleProcess()
    {
        return $this->moduleProcess;
    }

    /**
     * @param ModuleProcess $moduleProcess
     */
    public function setModuleProcess(ModuleProcess $moduleProcess)
    {
        $this->moduleProcess = $moduleProcess;
    }

    /**
     * @return string
     */
    public function getProcess()
    {
        return $this->process;
    }

    /**
     * @param string $process
     */
    public function setProcess($process)
    {
        $this->process = $process;
    }

    /**
     * @return string
     */
    public function getModule()
    {
        return $this->module;
    }

    /**
     * @param string $module
     */
    public function setModule($module)
    {
        $this->module = $module;
    }

    /**
     * @return string
     */
    public function getWaitingProcess()
    {
        return $this->waitingProcess;
    }

    /**
     * @param string $waitingProcess
     */
    public function setWaitingProcess($waitingProcess)
    {
        $this->waitingProcess = $waitingProcess;
    }

    /**
     * @return float
     */
    public function getAmount()

Resources/views/garments/report/supplier-financial/excel.html.twig
<table>
    <thead>
    <tr>
        <th colspan="4" align="center">Unifill Tex Group</th>
    </tr>
    <tr>
        <th colspan="4" align="center">Address: Nassa Heights 47, Level - 03, Bir Uttam AK Khandakar Rd, Dhaka 1212
        </th>
    </tr>
    <tr>
        <th></th>
    </tr>
    <tr>
    <tr>
        <th>{{ 'SL'|trans }}</th>
        <th>{{ 'Supplier Name'|trans }}</th>
        <th>{{ 'Amount'|trans }}</th>
        <th>{{ 'No of W/O'|trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% if entities is not empty %}
        {% for entity in entities %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ entity.company }}</td>
                <td>{{ entity.amount|number_format(2) }}</td>
                <td>{{ entity.count }}</td>
            </tr>
        {% endfor %}
    {% endif %}
    </tbody>
</table>

Resources/views/garments/report/supplier-financial/index.html.twig
{% extends 'layout.html.twig' %}
{% block body %}
    <div class="pcoded-inner-content">
        <!-- [ Main Content ] start -->
        <div class="row">
            <div class="card">
                <div class="card-header">
                    <h5>{{ 'Supplier W/O Summary Report'|trans }}</h5>
{#                    {% if entities is not empty %}#}
                        <div class="card-header-right">
                            <div class="btn-group btn-group-sm float-right" role="group" aria-label="Button group with nested dropdown">
                                <a target="_blank" href="{{ path('supplier_financial_report',{'mode': 'pdf','filterBy': filterBy}) }}" class="btn blue-bg white-font btn-sm"><i class="fa fa-file-pdf"></i> PDF</a>
                                <a target="_blank" href="{{ path('supplier_financial_report',{'mode': 'excel','filterBy': filterBy}) }}" class="btn btn-sm bg-primary white-font"><i class="fa fa-file-excel"></i> Excel</a>
                            </div>
                        </div>
{#                    {% endif %}#}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="card">
                <div class="card-block">
                    <div class="px-0 py-3">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_start(searchForm) }}
                                <table class="table table-striped table-bordered table-hover display nowrap item-wise-pr-report-filter">
                                    <thead class="thead-transparent">
                                    <tr role="row">
                                        <th>{{ form_label(searchForm.startDate,'From Date: ') }}</th>
                                        <th><div class="date-group">{{ form_widget(searchForm.startDate) }}</div></th>
                                        <th></th>
                                        <th></th>
                                        <th>{{ form_label(searchForm.endDate,'To Date: ') }}</th>
                                        <th><div class="date-group">{{ form_widget(searchForm.endDate) }}</div></th>
                                    </tr>
                                    <tr role="row">
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th></th>
                                        <th class="text-right">{{ form_widget(searchForm.filter,{'label':'Search'}) }}</th>
                                        {{ form_widget(searchForm._token) }}
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                    {% if entities is not empty %}
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-striped table-bordered" >
                                    <thead class="thead-green">
                                    <tr>
                                        <th scope="col">S/N</th>
                                        <th scope="col">Supplier Name</th>
                                        <th scope="col">No of Workorder</th>
                                        <th scope="col">Amount</th>
                                        <th scope="col">Percent</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                        {% set percent = 0 %}
                                        {% for entity in entities['suppliers'] %}
                                            {% set percent = percent + ((entity.amount * 100)/entities['workOrderAmount']['amount'])|default(0) %}
                                            <tr>
                                                <td>{{ loop.index }}</td>
                                                <td>{{ entity.company }}</td>
                                                <td>{{ entity.totalCount }}</td>
                                                <td>{{ entity.amount|number_format(2) }}</td>
                                                <td>{{ ((entity.amount * 100)/entities['workOrderAmount']['amount'])|default(0)|number_format(2) }}%</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                    <tr><th colspan="3"> Total Amount</th><th>{{ entities['workOrderAmount']['amount']|number_format(2) }}</th><th>
                                        {{ percent|number_format(2) }}%</th></tr>
                                </table>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <!-- [ Main Content ] end -->
    </div>
{% endblock %}
{% block cssBlock %}
    <style>
        table.item-wise-pr-report-table{
            position: relative;
        }
        table.item-wise-pr-report-table thead tr th {
            position: sticky;
            top: 0;
        }
        table.item-wise-pr-report-filter thead tr th{
            border: 0 !important;
        }
        table.item-wise-pr-report-filter thead tr th:nth-child(odd) {
            /*text-align: right;*/
            width: 13%;
        }
    </style>
    <link rel="stylesheet" href="{{ asset('assets/module/css/app.css') }}">
{% endblock  %}
{% block javascripts %}
    {{ parent() }}
    <script type="application/javascript" src="{{ asset('assets/module/js/app.js') }}"></script>
{% endblock  %}
{% block documentready %}
    {{ parent() }}
{% endblock %}

Resources/views/garments/report/supplier-financial/pdf.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Report-Item Wise</title>
    <style>
        table tbody tr td{
            padding: 2px;
        }
    </style>
</head>
<body>
<div style="padding-bottom: 10px"><img width="100%" src="{{ asset(headerImage) }}"></div>
{#<div class="print-footer-content"><div class="row"><div class="col-md-12"><img width="100%" src="{{ asset(headerImage) }}"></div></div></div>#}
<table border="1" cellspacing="0" cellpadding="0" width="100%">
    <thead>
    <tr>
        <th>{{ 'SL'|trans }}</th>
        <th>{{ 'Supplier Name'|trans }}</th>
        <th>{{ 'Amount'|trans }}</th>
        <th>{{ 'No of W/O'|trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% if entities is not empty %}
        {% for entity in entities %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ entity.company }}</td>
                <td>{{ entity.amount|number_format(2) }}</td>
                <td>{{ entity.count }}</td>
            </tr>
        {% endfor %}
    {% endif %}
    </tbody>
</table>
<div style="padding-top: 10px"><img width="100%" src="{{ asset(footerImage) }}"></div>
</body>
</html>